### ISSUE TITLE
vio-slam

### ISSUE THREAD

**Issue by liangyongshi** [ToniRV/NeRF-SLAM#14]
I0103 15:19:20.003431 146533 pipeline_module.py:85] Module: VioSLAM - Spinning. Segmentation fault (core dumped)

**Comment by ToniRV** [comment]
Ah! Can you provide a stack trace? perhaps with gdb?

**Comment by liangyongshi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，已经收到您的邮件，无法亲自回复，还请见谅。

**Comment by liangyongshi** [comment]
ubuntu 20.04, torch 12.1,
CUDA 11.6,  1 RTX3090,
I have only one GPU, so modify the code as the picture
![modified](https://user-images.githubusercontent.com/22517548/210746104-9b02af62-b38d-4a24-b9c3-f5635cf0e682.png)
run the code
python ./examples/slam_demo.py --dataset_dir=./Datasets/Replica/office0 --dataset_name=nerf --buffer=100  --weights=./droid.pth --img_stride=2 --fusion='nerf'  --slam --gui --parallel_run

results
![result](https://user-images.githubusercontent.com/22517548/210747155-8d7bf2e1-c0ae-4301-8849-725ecf8af60b.png)

**Comment by liangyongshi** [comment]
when I close the parallel_run, the result is
![Screenshot from 2023-01-05 17-33-46](https://user-images.githubusercontent.com/22517548/210747954-7a3c288f-ca61-464f-a509-3dd16120a8c1.png)

Looking forward to your reply

**Comment by ZhenhuiL1n** [comment]
I am also facing this problem, did anyone solve it yet?

**Comment by ZhenhuiL1n** [comment]
![bug](https://user-images.githubusercontent.com/56009715/211189702-741a8c1a-d853-4124-b7e3-385853fd76f8.png)

**Comment by ZhenhuiL1n** [comment]
![bug1](https://user-images.githubusercontent.com/56009715/211189819-6587cb84-cf16-4ce0-b3c9-20164322eed0.png)

**Comment by liangyongshi** [comment]
> I am also facing this problem, did anyone solve it yet?

something wrong with torch_scatter and droid_backends,  adopt conda to insatll torch_scatter, and I don't know how to solve the other problem of droid_backends

**Comment by ZhenhuiL1n** [comment]
> > I am also facing this problem, did anyone solve it yet?
> 
> something wrong with torch_scatter and droid_backends, adopt conda to insatll torch_scatter, and I don't know how to solve the other problem of droid_backends

I think it should be a specific version, cause I used the conda to install troch_scatter and other bug pops up

**Comment by phamquandung** [comment]
For me, I use two GPU and the problem is solved

**Comment by parastoobakhtiarii** [comment]
> > I am also facing this problem, did anyone solve it yet?
> 
> something wrong with torch_scatter and droid_backends, adopt conda to insatll torch_scatter, and I don't know how to solve the other problem of droid_backends

Hi, I am trying to run demo, but it seems like the droid-backends is a module specified for this nerf-slam which is some how missed and the setup.py can't find it. Do you know how I can handle this problem? 
Thank you.

**Comment by liangyongshi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，已经收到您的邮件，无法亲自回复，还请见谅。
