### ISSUE TITLE
how much time does it take to run demo?

### ISSUE THREAD

**Issue by ggsonic** [ToniRV/NeRF-SLAM#26]
using my rtx3090 pc,it has been running a week but still not finishing. how much time does it take to run the  demo? `python ./examples/slam_demo.py --dataset_dir=./datasets/Replica/office0 --dataset_name=nerf --buffer=100 --slam --parallel_run --img_stride=2 --fusion='nerf' `

**Comment by XinyueZ** [comment]
@ggsonic didnt you face this issue before https://github.com/ToniRV/NeRF-SLAM/issues/21 ?

**Comment by ToniRV** [comment]
It should be running in real-time and displaying the map in the GUI while running... Something is wrong if you don't see anything after 30 seconds.
