### ISSUE TITLE
where do you use the uncertainty for camera pose in volumetric nerf?

### ISSUE THREAD

**Issue by dong-won-shin** [ToniRV/NeRF-SLAM#27]
In the paper, I couldn't find the usage of camera pose uncertainty.
but I found the depth uncertainty in the loss function for depth loss.
<img width="343" alt="image" src="https://user-images.githubusercontent.com/100552998/212488660-bb73731f-0c32-4101-a0b6-9d07a1b48b37.png">

Thanks for your great research!

**Comment by ToniRV** [comment]
Hi @dong-won-shin, I didn't have time to weigh the pose optimization by the pose uncertainty.
