### ISSUE TITLE
Any description about the GPU usage?

### ISSUE THREAD

**Issue by panxkun** [ToniRV/NeRF-SLAM#3]
As I know, the original droid-slam need at least ~10GB gpu to inference and instant-ngp need extra more memory. So how much gpu memory it will cost if it runs.  I have successfully installed the environment but it crashed when loading the dataset.  It seems to be related to multigpu usage in instant-ngp part. could you give me some advice ? 

I run the code in my desktop machine with a gtx 2070 8GB and below information is output

![image](https://user-images.githubusercontent.com/44204704/204758369-1b3ddb3b-4a37-472d-a2b1-ce851fb1ea96.png)

**Comment by xiehousen** [comment]
> > 
> 
> Thanks, checking out the branch of instant-ngp fixed the above problem.

It does not works for me. Do you have any idea about this problem?
