### ISSUE TITLE
AttributeError: 'pyngp.Training' object has no attribute 'update_training_images'

### ISSUE THREAD

**Issue by dennisushi** [ToniRV/NeRF-SLAM#36]
`AttributeError: 'pyngp.Training' object has no attribute 'update_training_images'` 
in 
`File "/home/dennisushi/repos/temp/ngp/NeRF-SLAM/./examples/../fusion/nerf_fusion.py", line 285, in send_data
    self.ngp.nerf.training.update_training_images(frame_ids.cpu().numpy().tolist(),` 
when running 
`python3 ./examples/slam_demo.py --dataset_dir=./Datasets/Replica/office0 --dataset_name=nerf --buffer=100 --slam --parallel_run --img_stride=2 --fusion='nerf' --multi_gpu --gui`. 

I tried to replace instant-ngp with the latest one, and that didn't work either

**Comment by dennisushi** [comment]
`grep -ir "update_training_images" thirdparty/instant-ngp` gives no results

**Comment by shreyasaha1997** [comment]
I get the same error as well. You need to use the following repo - https://github.com/ToniRV/instant-ngp/tree/feature/nerf_slam
