### ISSUE TITLE
Nothing to see in the instant-ngp

### ISSUE THREAD

**Issue by richard7714** [ToniRV/NeRF-SLAM#8]
While following the readme, I got this error in the instant-NeRF gui.
![1](https://user-images.githubusercontent.com/58978349/209956438-58ebb6e0-1562-4a16-9b5a-df9081450a3d.png)

With this error, i also have this error code.
![2](https://user-images.githubusercontent.com/58978349/209956706-d3c12ecc-1fdb-4043-a1fc-b2858e7c5416.png)

I tried with gtsam fork, and also with borglab/gtsam, but couldn't fix this problem.

If anyone knows solution, comment me. Thanks.

**Comment by phamquandung** [comment]
Hi @richard7714, can you solve this problem?

**Comment by richard7714** [comment]
@phamquandung yes, it was the problem of gtsam/gtsam/linear/linear.i.

Like this comment https://github.com/ToniRV/NeRF-SLAM/issues/5#issuecomment-1367263684, I added `Vector vector(const gtsam::KeyVector& keys) const;` to line 239 of 
thirdparty/gtsam/gtsam/linear/linear.i and add `gtsam::VectorValues optimizeDensely() const;` to 405 of thirdparty/gtsam/gtsam/linear/linear.i.

On top of it, i also deleted `  Vector vector() const;` of line 238 in linear.i

For the gtsam version, I used author's default fork version

**Comment by phamquandung** [comment]
Hi @richard7714, even though I fork the new version of gtsam and ngp. I still have this issue. How about your result? 
![image](https://user-images.githubusercontent.com/28943896/210733787-b4bd6408-96ac-4364-b93c-5205454c8d52.png)

**Comment by richard7714** [comment]
@phamquandung, Check your terminal and see if there is any error code. I guess it's the problem of your slam module. If it works properly, It goes like this
![1](https://user-images.githubusercontent.com/58978349/210756826-fa1a948b-2f45-4ea1-b0a8-a7cdaf29d2ef.png)

**Comment by songlin** [comment]
@phamquandung Hi, Do you solve the problem? I might have the same problem as you.  I keep getting 
```
Fusion packet from SLAM module is None...
```
and nothing shows in the GUI.
